name: Build & test

on:
  push:
    branches:
      - main
      - snapshot
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: linux
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            spotlessCheck
            assemble
            test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            **/build/test-results/*
            **/build/reports/*

    deploy:
      if: github.event_name == 'push' # only deploy for pushed commits (not PRs)
      runs-on: ubuntu-latest
      needs: [ build ]
      timeout-minutes: 30
      env:
          TERM: dumb

      steps:
        - uses: actions/checkout@v2

        - name: Copy CI gradle.properties
          run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

        - name: Setup JDK
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - uses: burrunan/gradle-cache-action@v1
          name: Deploy to Sonatype
          env:
            ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
            ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
            ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
            ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
            ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
          with:
            job-id: linux
            gradle-dependencies-cache-key: |
              gradle/libs.versions.toml
            arguments: publish --no-parallel
