name: Update release with binaries

on:
  push:
    tags:
      - v*

jobs:
  update_release:
      runs-on: ubuntu-latest
      timeout-minutes: 30
      env:
          TERM: dumb

      steps:
          - uses: actions/checkout@v3

          - name: Copy CI gradle.properties
            run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

          - name: Setup JDK
            uses: actions/setup-java@v3
            with:
                distribution: 'zulu'
                java-version: 11

          - uses: gradle/gradle-build-action@v2

          - name: Add artifact version to ENV
            run: echo "VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

          - name: Build the fat jars for CLI usage
            if: success() && !endsWith(env.VERSION, '-SNAPSHOT')
            run: ./gradlew clean :rules:ktlint:shadowJar :rules:detekt:shadowJar -PuberJar --rerun-tasks

          - name: Upload ktlint binaries to release
            if: success() && !endsWith(env.VERSION, '-SNAPSHOT')
            uses: svenstaro/upload-release-action@v2
            with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: rules/ktlint/build/libs/ktlint-${{ env.VERSION }}-all.jar
                tag: v${{ env.VERSION }}
                overwrite: true

          - name: Upload detekt binaries to release
            if: success() && !endsWith(env.VERSION, '-SNAPSHOT')
            uses: svenstaro/upload-release-action@v2
            with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: rules/detekt/build/libs/detekt-${{ env.VERSION }}-all.jar
                tag: v${{ env.VERSION }}
                overwrite: true
